services:
  python:
    container_name: mypython
    build: .
    ports:
      - "8080:80"
    environment:
      - OUTPUT_DIR=/process/videos
      - DIRECTORY=/directory
    volumes:
      - myredis:/data
      - ~/Videos/process:/process/videos
      - ~/test:/directory
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  redis:
    container_name: myredis
    image: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
networks:
  default:
    name: my-net
volumes:
  myredis:
