services:
  nginx:
    container_name: mynginx
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ~/Videos/process:/process/videos
      # debug, enable in docker development
      # because server will automatically refresh
      # make you enable tailwind compiler
      - ./nginx/templates:/usr/share/nginx/html
  python:
    container_name: mypython
    build: .
    environment:
      - OUTPUT_DIR=/process/videos
      - DIRECTORY=/directory
    ports:
      # debug only, open to outside world
      - "5000:5000"
    volumes:
      # most important parameter
      # change it to your folders
      - ~/Videos/process:/process/videos
      - ~/test:/directory
      #

      # debug, enable in docker development
      # because server will automatically refresh
      - ./server.py:/pythonapp/server.py
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
  redis:
    container_name: myredis
    image: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - myredis:/data
networks:
  default:
    name: my-net
volumes:
  myredis:
